### ISSUE TITLE
[REQ] fix license file

### ISSUE THREAD

**Issue by MarcoRavich** [mmende/soundengine#3]
Hi there, 1st of all thanks for your cool work !

Since we've "doxed" it in our [HyMPS project](https://github.com/forart/HyMPS#readme) (under the [AUDIO](https://github.com/forart/HyMPS#-) \ [Libraries](https://github.com/forart/HyMPS/blob/main/AudioLIBs.md#--) \ [Others subsection](https://github.com/forart/HyMPS/blob/main/AudioLIBs.md#others-)), can you replace the license with a "GH-compliant" one ?

Although it may sounds like a minor aspect, a "uncompliant" license file causes an inconsistent generation of the relative badge:

![](https://flat.badgen.net/github/license/mmende/soundengine/?label=LICENSE)
(badge-generator URL: https://flat.badgen.net/github/license/mmende/soundengine/?label=LICENSE)

You can easily set a "correct" (= compliant) one through the GH's license wizard tool.

Last but not least, let us know how - in your opinion - we could improve categorization/sorting of collected projects in order to push their evolution by favouring collaborations between developers (and not only).

Thanks in advance.

**Comment by MarcoRavich** [comment]
Bump.

Request updated.

**Comment by mmende** [comment]
I updated the license file using GH's MIT template. Hope this helps

**Comment by MarcoRavich** [comment]
Thanks a lot, as you can see it works now (click the badge-generator URL) !
